# Generated by Django 6.0.5 on 2026-08-12 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_endereco_alter_servico_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e espaços.', regex='^[A-Za-zÀ-ÿ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='servico',
            name='notas',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='servico',
            name='protocolo',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve conter apenas números.', regex='^\\d+$')]),
        ),
    ]
