# Generated by Django 6.0.5 on 2026-08-12 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_nome_alter_servico_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve conter apenas números.', regex='^\\d+$')]),
        ),
    ]
