# Generated by Django 6.0.5 on 2026-06-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JB_Chopeiras', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
