# Generated by Django 6.0.5 on 2026-05-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=20)),
                ('tempo_de_fidelidade', models.IntegerField()),
                ('servicos_realizados', models.IntegerField()),
            ],
        ),
    ]
