# Generated by Django 6.0.5 on 2026-08-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_clientes_deletado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='servicos_realizados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tempo_de_fidelidade',
            field=models.IntegerField(default=0),
        ),
    ]
